[workspace]
package.edition = "2024"
resolver = "3"
members = [
    "_lib",
    # topics
    "algorithms",
    "data-structures",
    "design-patterns",
    "macros",
    "problem-solving",
    # Advanced
    "advanced/meta-programming",
    # projects
    "projects/pandas",
    "projects/ruscrypt",
    "projects/vault",
    "projects/todo-web", "advanced",
]
