[workspace]
resolver = "3"

members = ["crates/*", "projects/*", "crates/advanced/*"]
exclude = ["crates/advanced"]

[workspace.package]
version = "0.9.0"
authors = ["Sudip Ghimire"]
edition = "2024"
rust-version = "1.85"


[workspace.dependencies]
utils = { path = "./crates/utils" }
