[package]
name = "advanced"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "ownership"
path = "memory-management/ownership.rs"

[[bin]]
name = "unsafe"
path = "memory-management/unsafe.rs"
