[package]
name = "types-and-generics"
version = "0.1.0"
edition = "2024"

[dependencies]


# ----------------------------[ Types and Generics ]----------------------------

[[bin]]
name = "generics"
path = "src/generics.rs"

[[bin]]
name = "traits"
path = "src/traits.rs"
