[package]
name = "todo"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4"
actix-files = "0.6.6"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
