[package]
name = "operator-overloading"
version.workspace = true
edition.workspace = true

[dependencies]


# --------------------------[ Systems and Low Levels ]--------------------------

[[bin]]
name = "operator-overloading"
path = "src/main.rs"
