[package]
name = "operator-overloading"
version = "0.5.0"
edition = "2024"

[dependencies]


# --------------------------[ Systems and Low Levels ]--------------------------

[[bin]]
name = "operator-overloading"
path = "src/main.rs"
