[package]
name = "macros"
version = "0.9.0"
edition = "2024"

[dependencies]
shape = { path = "./shape" }
shape_derive = { path = "./shape_derive" }


[[bin]]
name = "procedural_derive"
path = "src/procedural_derive.rs"
