[package]
name = "types-and-generics"
version.workspace = true
edition.workspace = true

[dependencies]


# ----------------------------[ Types and Generics ]----------------------------

[[bin]]
name = "generics"
path = "src/generics.rs"

[[bin]]
name = "traits"
path = "src/traits.rs"
