[package]
name = "operator-overloading"
version = "0.1.0"
edition = "2024"

[dependencies]


# --------------------------[ Systems and Low Levels ]--------------------------

[[bin]]
name = "struct-overloading"
path = "src/struct-overloading.rs"
