[package]
name = "vault"
version = "0.6.0"
edition = "2024"

[dependencies]
common = { workspace = true }
crypto = "0.5.1"
argon2 = "0.5.3"
cipher = "0.4.4"
rand = "0.9.0"
aes-gcm = "0.10.3"
hex = "0.4.3"
rpassword = "7.3.1"
