[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
directories = "5.0.1"
crypto = "0.5.1"
argon2 = "0.5.3"
cipher = "0.4.4"
rand = "0.8.5"
aes-gcm = "0.10.3"
hex = "0.4.3"
